# General GitHub Repository Settings
repository:
  license: MIT      # Select a license from the options below

# MATLAB Toolbox Settings
matlab_toolbox:
  namespace_name: omkgsync                          # A unique namespace for your toolbox
  toolbox_name: openMINDS_KG_Sync                   # Name of the MATLAB toolbox                  
  author_name: Eivind Hennestad                     
  author_email: eivihe@uio.no         
  author_company: University of Oslo / Neural Systems 
  toolbox_summary: Sync openMINDS metadata to and from EBRAINS KG
  toolbox_description: |
    Provides methods for authenticating with EBRAINS services and upload and download metadata to the EBRAINS Knowledge Graph using openMINDS metadata types
  dependencies: null

# Publishing options
codecov:
  badge_token: JZNUFC2953

fileexchange:
  fex_url: null
