function runLiveIntegrationTests()
    projectRootDir = omkgsynctools.projectdir();
    matbox.tasks.testToolbox(projectRootDir, ...
        "CreateBadge", false, ...
        "HasTag", "LiveIntegration")
end
