function mustBeValidUUID(identifier)
    % UUID regex: 8-4-4-4-12 hex digits (RFC 4122 format)
    uuidPattern = "^[0-9a-fA-F]{8}-" + ...
                  "[0-9a-fA-F]{4}-" + ...
                  "[0-9a-fA-F]{4}-" + ...
                  "[0-9a-fA-F]{4}-" + ...
                  "[0-9a-fA-F]{12}$";

    if ~contains(identifier, regexpPattern(uuidPattern))
        error("OMKG:validator:InvalidUUID", ...
              "Identifier must be a valid UUID. Got: %s", identifier);
    end
end
